In [ ]:
# Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np
a = np.random.randint(1, 100, size = (3,3))
a

array([[97, 26,  1],
       [91, 37, 93],
       [11,  6,  9]])

In [ ]:
a.T

array([[97, 91, 11],
       [26, 37,  6],
       [ 1, 93,  9]])

In [ ]:
# Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

b = np.random.randint(1, 10, size = (10))
b

array([1, 2, 3, 2, 2, 1, 7, 9, 4, 6])

In [ ]:
b.reshape(2, 5)

array([[1, 2, 3, 2, 2],
       [1, 7, 9, 4, 6]])

In [ ]:
b.reshape(5,2)

array([[1, 2],
       [3, 2],
       [2, 1],
       [7, 9],
       [4, 6]])

In [4]:
# Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np
c = np.random.rand(4,4)
c

array([[0.69140401, 0.73265314, 0.63452033, 0.72096341],
       [0.439102  , 0.76628948, 0.4992672 , 0.95788818],
       [0.69167811, 0.69421189, 0.40220397, 0.14609512],
       [0.07912368, 0.5315439 , 0.05615533, 0.18386308]])

In [5]:
bordered_array = np.pad(c, pad_width=1, mode='constant', constant_values=0)

print(bordered_array)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.69140401 0.73265314 0.63452033 0.72096341 0.        ]
 [0.         0.439102   0.76628948 0.4992672  0.95788818 0.        ]
 [0.         0.69167811 0.69421189 0.40220397 0.14609512 0.        ]
 [0.         0.07912368 0.5315439  0.05615533 0.18386308 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [6]:
# Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np
d = np.arange(10, 61, 5)
print(d)

[10 15 20 25 30 35 40 45 50 55 60]


In [7]:
# Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

array = np.array(['python', 'numpy', 'pandas'])

uppercase = np.char.upper(array)
lowercase = np.char.lower(array)
titlecase = np.char.title(array)

print("Uppercase:", uppercase)
print("Lowercase:", lowercase)
print("Title Case:", titlecase)

Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


In [8]:
# Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

words = np.array(['hello', 'i', 'am', 'Aarti'])

spaced_words = np.char.join(' ', words)

print(spaced_words)

['h e l l o' 'i' 'a m' 'A a r t i']


In [9]:
# Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

addition = array1 + array2

subtraction = array1 - array2

multiplication = array1 * array2

division = array1 / array2

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nAddition:")
print(addition)
print("\nSubtraction:")
print(subtraction)
print("\nMultiplication:")
print(multiplication)
print("\nDivision:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Addition:
[[ 8 10 12]
 [14 16 18]]

Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Multiplication:
[[ 7 16 27]
 [40 55 72]]

Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [10]:
# Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

identity_matrix = np.eye(5)

diagonal_elements = np.diagonal(identity_matrix)

print("Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [11]:
# Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np

random_integers = np.random.randint(0, 1001, size=100)

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random Integers:")
print(random_integers)
print("\nPrime Numbers:")
print(prime_numbers)


Random Integers:
[558 288 308 357 475 689 519 558   6 543 872 458 577  99  62 461 695 908
  49  19 100 363 529 796 260  30 341 495 359 682 409 602 270 458 337 249
 991 984  46 262 249 975 573 163 291 880 400 758 376 865 440 631 133 909
 524 486 400 266 853 641 206 252 518 310 478 517 892 314 565 914 292 598
 238 878  57  90 212 861 198  85 765 188 579 852 601  70 733 699 499 605
 508 769 329 512 374 941 115   4 740 751]

Prime Numbers:
[577, 461, 19, 359, 409, 337, 991, 163, 631, 853, 641, 601, 733, 499, 769, 941, 751]


In [15]:
# Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np

daily_temperatures = np.random.uniform(low=0, high=100, size=30)

weekly_temperatures = daily_temperatures.reshape(5, 6)

weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Daily Temperatures:")
print(daily_temperatures)
print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures:
[41.5343424  87.63321346 37.06718786 55.13562191 97.21043302 95.84363044
 32.49620113 96.08460707 70.12142121 55.9862263  63.93148233 64.58558406
 30.48493753  8.43978982 40.07356877 21.58167239 44.78333717 92.30837685
 34.37214044 25.87897279 25.58335502 70.83984074 71.13058337 29.68675435
 84.30919769 55.13554796 37.0888294  76.7422083  17.3932979  56.10469509]

Weekly Averages:
[69.07073818 63.86758702 39.61194709 42.91527445 54.46229606]
